"""Add VMRequest model

Revision ID: eb7453a24d50
Revises: 8840cf6925dc
Create Date: 2025-12-21 17:38:39.538113

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'eb7453a24d50'
down_revision = '8840cf6925dc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('vm_request',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('machine_type', sa.String(length=50), nullable=False),
    sa.Column('machine_name', sa.String(length=50), nullable=False),
    sa.Column('machine_cpu', sa.Integer(), nullable=False),
    sa.Column('machine_ram', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('vm_ip', sa.String(length=50), nullable=True),
    sa.Column('vm_hostname', sa.String(length=100), nullable=True),
    sa.Column('vm_user', sa.String(length=50), nullable=True),
    sa.Column('vm_password', sa.String(length=100), nullable=True),
    sa.Column('vm_vmid', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.alter_column('password',
               existing_type=sa.VARCHAR(length=120),
               nullable=False)
        batch_op.drop_column('age')
        batch_op.drop_column('email')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('email', sa.VARCHAR(length=120), nullable=False))
        batch_op.add_column(sa.Column('age', sa.INTEGER(), nullable=True))
        batch_op.alter_column('password',
               existing_type=sa.VARCHAR(length=120),
               nullable=True)

    op.drop_table('vm_request')
    # ### end Alembic commands ###
